main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("register/pengguna/", views.registrasi_pengguna, name="registrasi-pengguna"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("bantuan/", views.bantuan, name="bantuan"),
    path("pengaturan/", views.pengaturan, name="pengaturan"),
]

mobile_sporteev/urls.py
from django.contrib import admin
from django.urls import path, include

import sportivity

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('home/', include('sportivity.urls')),
    path('sportivity/', include('sportivity.urls')),
    path('profil/', include('profil.urls')),
    path('sport-buddies/', include('sport_buddies.urls')),
    path('sportwiki/', include('sportwiki.urls')),
    path('sport-venue/', include('sport_venue.urls')),
    path('admin-dashboard/', include('admin_dashboard.urls')),
]

sport_venue/urls.py
from django.urls import path

from . import views

app_name = 'sport_venue'

urlpatterns = [
    path("", views.venue_filter, name="venue-filter"),
    path("list-venue/", views.list_venue, name="list-venue"),
    path("venue-details/<int:id_venue>", views.venue_details, name="venue-details"),
    path("upload-data-venue/", views.upload_data_venue, name="upload-data-venue"),
]

sport_venue/models.py
from pyexpat import model
from typing import Callable
from django.db import models
from django.db.models.deletion import CASCADE
from main.models import Pengguna
from django_dropbox_storage.storage import DropboxStorage
# from location_field.models.plain import PlainLocationField
from django.db.models.fields.related import ManyToManyField

# Create your models here.

class Venue(models.Model):
    nama_venue = models.CharField(max_length=50, null=False)
    provinsi = models.CharField(max_length=50, null=False)
    kabupaten_kota = models.CharField(max_length=50, null=False)
    kecamatan = models.CharField(max_length=50, null=False)
    alamat = models.CharField(max_length=100, null=False)
    no_telepon = models.CharField(max_length=50, null=False)
    harga = models.CharField(max_length=200, null=False)
    jenis_olahraga = models.CharField(max_length=100, null=False)
    jadwal = models.CharField(max_length=200, null=False)
    kontak_coach = models.CharField(max_length=50, null=False)
    fasilitas = models.CharField(max_length=200, null=False)
    sewa_alat = models.CharField(max_length=200, null=False)
    link_foto= models.CharField(max_length=200, null=False)
    keterangan_tambahan = models.CharField(max_length=200, null=False)

class Lapangan(models.Model):
    venue = models.ForeignKey(Venue, on_delete=CASCADE, blank=False)
    nama_lapangan = models.CharField(max_length=50, null=False)

sport_venue/views.py
from email import message
from django.http import request, HttpResponse
from django.shortcuts import redirect, render, resolve_url
from django.views.decorators.csrf import csrf_exempt
from pyexcel_xls import get_data as xls_get
from pyexcel_xlsx import get_data as xlsx_get
from django.utils.datastructures import MultiValueDictKeyError
from .models import Venue
from import_export import resources
from .resources import VenueResource
from django.contrib import messages
from tablib import Dataset

def venue_filter(request):
    return render(request, 'sport_venue/venue-filter.html')

def list_venue(request):
    list_venue = list(Venue.objects.all())
    context = {
        'list_venue':list_venue
    }
    return render(request, 'sport_venue/list-venue.html', context)

def venue_details(request, id_venue):
    tmp_venue = Venue.objects.filter(id=id_venue)
    venue = tmp_venue[0]
    nama_venue = venue.nama_venue
    provinsi = venue.provinsi
    kabupaten_kota = venue.kabupaten_kota
    kecamatan = venue.kecamatan
    alamat = venue.alamat
    no_telepon = venue.no_telepon
    harga = venue.harga
    jenis_olahraga = venue.jenis_olahraga
    jadwal = venue.jadwal
    kontak_coach = venue.kontak_coach
    fasilitas = venue.fasilitas
    sewa_alat = venue.sewa_alat
    link_foto = venue.link_foto
    keterangan_tambahan = venue.keterangan_tambahan
    
    context = {
        'nama_venue':nama_venue,
        'provinsi':provinsi,
        'kabupaten_kota':kabupaten_kota,
        'kecamatan':kecamatan,
        'alamat':alamat,
        'no_telepon':no_telepon,
        'harga':harga,
        'jenis_olahraga':jenis_olahraga,
        'jadwal':jadwal,
        'kontak_coach':kontak_coach,
        'fasilitas':fasilitas,
        'sewa_alat':sewa_alat,
        'link_foto':link_foto,
        'keterangan_tambahan':keterangan_tambahan
    }
    return render(request, 'sport_venue/venue-details.html', context)

def upload_data_venue(request):
    if request.method == 'POST':
        venue_resource = VenueResource()
        dataset = Dataset()
        new_venue = request.FILES['file_db']

        # if not (new_venue.name.endswith('xlsx') or new_venue.name.endswith('xls')):
        if not new_venue.name.endswith('xlsx'):
            messages.info(request, 'wrong format')
            return render(request, 'sport_venue/upload.html')
        
        Venue.objects.all().delete()
        imported_data = dataset.load(new_venue.read(), format='xlsx')
        for data in imported_data:
            #cek apakah masih ada data selanjutnya atau engga
            if data[1] == None:
                break
            venue = Venue(
                data[0],
                data[1],
                data[2],
                data[3],
                data[4],
                data[5],
                data[6],
                data[7],
                data[8],
                data[9],
                data[10],
                data[11],
                data[12],
                data[13],
                data[14],
                )
            venue.save()
    return render(request, 'sport_venue/upload.html')
        

sport_venue/templates/sport_venue/list-venue.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}List Venue{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

<div class="block">
    <div class="row">
        {% for venue in list_venue %}
        <a href="{% url 'sport_venue:venue-details' venue.id %}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{venue.nama_venue}}</div>
                <div class="card-body">
                <div class="post-thumb">
                    <a href="news-single.html">
                        <img src="{{venue.link_foto}}"
                            alt="post-image" class="img-fluid">
                    </a>
                </div>
                <h5 class="card-title">{{venue.jenis_olahraga}}</div></h5>
                <p class="card-text">{{venue.provinsi}}</p>
                <p class="card-text">{{venue.kabupaten_kota}}</p>
                <p class="card-text">{{venue.no_telepon}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock content %}

sport_venue/templates/sport_venue/upload.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}List Venue{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">
    <p{% if message.tags %} class=""{% endif %}> {{ message }} </p>
</div>
{% endfor %}
{% endif %}

<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file_db">
    <button type="submit">Upload</button>
    <h2>Please Upload File</h2>
</form>


{% endblock content %}

sport_venue/templates/sport_venue/venue-details.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}List Venue{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}
<h1>{{nama_venue}}</h1>
Provinsi : {{provinsi}} </br>
Kabupaten/Kota :{{kabupaten_kota}}</br>
Kecamatan : {{kecamatan}}</br>
Alamat : {{alamat}}</br>
Nomor Telepon :{{no_telepon}}</br>
Harga : {{harga}}</br>
Jenis Olahraga : {{jenis_olahraga}}</br>
Jadwal : {{jadwal}}</br>
Kontak Coach  : {{kontak_coach}}</br>
Fasilitas : {{fasilitas}}</br>
Sewa Alat : {{sewa_alat}}</br>
{% comment %} {{link_foto}} {% endcomment %}
Keterangan Tambahan : {{keterangan_tambahan}}</br>

{% endblock content %}

sport_venue/templates/sport_venue/venue-filter.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}List Venue{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

<div class="block">
    <div class="row">
        {% for venue in list_venue %}
        <a href="{% url 'sport-venue:venue-details' venue.nama_venue %}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{venue.nama_venue}}</div>
                <div class="card-body">
                <div class="post-thumb">
                    <a href="news-single.html">
                        <img src="{{venue.link_foto}}"
                            alt="post-image" class="img-fluid">
                    </a>
                </div>
                <h5 class="card-title">{{venue.jenis_olahraga}}</div></h5>
                <p class="card-text">{{venue.provinsi}}</p>
                <p class="card-text">{{venue.kabupaten_kota}}</p>
                <p class="card-text">{{venue.no_telepon}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock content %}