main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("register/pengguna/", views.registrasi_pengguna, name="registrasi-pengguna"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("bantuan/", views.bantuan, name="bantuan"),
    path("pengaturan/", views.pengaturan, name="pengaturan"),
]

mobile_sporteev/urls.py
from django.contrib import admin
from django.urls import path, include

import sportivity

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('home/', include('sportivity.urls')),
    path('sportivity/', include('sportivity.urls')),
    path('profil/', include('profil.urls')),
    path('sport-buddies/', include('sport_buddies.urls')),
    path('sportwiki/', include('sportwiki.urls')),
    path('sport-venue/', include('sport_venue.urls')),
    path('admin-dashboard/', include('admin_dashboard.urls')),
]

sport_buddies/urls.py
from urllib import request
from django.urls import path

from . import views

app_name = 'sport_buddies'

urlpatterns = [
    path("", views.list_buddies, name="list_buddies"),
    path("list-request/", views.list_request, name="list-request"),
    path("user-detail/<str:username_buddy>", views.user_detail, name="user-detail"),
    path("add-buddies/<str:username_buddy>", views.add_buddies, name="add-buddies"),
    path("accept-request/<str:username_buddy>", views.accept_request, name="accept-request"),
    path("reject-request:/<str:username_buddy>", views.reject_request, name="reject-request"),
    path("find-sport-buddies/", views.find_sport_buddies, name="find-sport-buddies"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),

]
 

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import ModelState
from django.db.models.enums import Choices
from django_dropbox_storage.storage import DropboxStorage

# Create your models here.

class CustomUser(AbstractUser):
    is_pengguna = models.BooleanField("user status", default=False)
    is_admin = models.BooleanField(default=False)
    alamat = models.TextField(max_length=250)
    no_telepon = models.TextField(max_length=15)
    # soon bakal ada is venue


class Pengguna(models.Model):
    DROPBOX_STORAGE = DropboxStorage()
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    tanggal_lahir = models.DateField()
    JENIS_KELAMIN = (
        (1, "Laki-laki"),
        (2, "Perempuan"),
    )
    jenis_kelamin = models.IntegerField(choices=JENIS_KELAMIN)
    is_active = True
    photo = models.ImageField(upload_to='photos', storage=DROPBOX_STORAGE)
    level = models.IntegerField(default=1)
    total_exp = models.IntegerField(default=0)
    current_exp = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

# soon
# class Venue(models.Model):
#     is_active = False

class PhotoTest(models.Model):
    DROPBOX_STORAGE = DropboxStorage()
    photo = models.ImageField(upload_to='photos', storage=DROPBOX_STORAGE, blank=True, null=True, default=None)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

sport_buddies/models.py
from pyexpat import model
from telnetlib import STATUS
from typing import Callable
from django.db import models
from django.db.models.deletion import CASCADE
from main.models import Pengguna
from django_dropbox_storage.storage import DropboxStorage
# from location_field.models.plain import PlainLocationField
from django.db.models.fields.related import ManyToManyField

# Create your models here.

class Buddy(models.Model):
    user_id = models.ForeignKey(Pengguna, related_name='%(class)s_requests_user_id',on_delete=CASCADE, blank=False)
    buddy_id = models.ForeignKey(Pengguna, related_name='%(class)s_requests_buddy_id',on_delete=CASCADE, blank=False)
    STATUS = (
        (0, "Draft"),
        (1, "Pending"),
        (2, "Rejected"),
        (3, "Accepted"),
    )
    status = models.IntegerField(choices=STATUS, default=0)
    
class SportCommunity(models.Model):
    nama_community = models.CharField(max_length=50, blank=False)
    RANK = (
        (0, "Jagoan di Hati Orang Tua"),
        (1, "Jagoan RW"),
        (2, "Jagoan Kompleks"),
        (3, "Jagoan Kecamatan"),
        (4, "Jagoan Kota"),
        (5, "Jagoan Provinsi"),
        (6, "Jagoan Nasioanal"),
        (7, "Jagoan Internasioanal"),
    )
    rank = models.IntegerField(choices=RANK, default=0)
    lokasi =  models.CharField(max_length=100, blank=False)
    level = models.IntegerField(default=1)
    exp = models.IntegerField(default=0)
    captain = models.ForeignKey(Pengguna, on_delete=CASCADE, blank=False)

    def __str__(self):
        return self.nama_community

# class RequestBuddy(models.Model):
#     user_id = models.ForeignKey(Pengguna, related_name='%(class)s_requests_user_id',on_delete=CASCADE, blank=False)
#     buddy_id = models.ForeignKey(Pengguna, related_name='%(class)s_requests_buddy_id',on_delete=CASCADE, blank=False)
#     STATUS = (
#         (0, "Draft"),
#         (1, "Pending"),
#         (2, "Rejected"),
#         (3, "Accepted"),
#     )
#     status = models.IntegerField(choices=STATUS, default=0)
#     def __str__(self):
#         return self.buddy_id

sport_buddies/views.py
from django.http import request, HttpResponse
from django.shortcuts import redirect, render, resolve_url
from django.views.decorators.csrf import csrf_exempt
from django.utils.datastructures import MultiValueDictKeyError
from .models import Buddy, SportCommunity
from main.models import CustomUser, Pengguna

# Create your views here.

def find_sport_buddies(request):
    pengguna = Pengguna.objects.get(user=request.user)
    list_pengguna = list(Pengguna.objects.all().exclude(user=pengguna.user))
    context = {
        'list_pengguna':list_pengguna 
    }
    return render(request, 'sport_buddies/find-sport-buddies.html', context)

def list_buddies(request):
    pengguna = Pengguna.objects.get(user=request.user)
    list_buddy_tmp = list(Buddy.objects.filter(user_id=pengguna).filter(status=3))
    list_buddy = []
    for buddy in list_buddy_tmp :
        list_buddy.append(buddy.buddy_id)

    context = {
        'list_buddy':list_buddy
    }
    return render(request, 'sport_buddies/list-buddies.html', context)

def user_detail(request,username_buddy):
    user_buddy = CustomUser.objects.get(username=username_buddy)
    buddy = Pengguna.objects.get(user=user_buddy)
    foto = ""
    print(foto)
    try:
        foto = buddy.photo.url
    except:
        foto = False

    context = {
        'foto': foto,
        'nama_depan': buddy.user.first_name,
        'nama_belakang': buddy.user.last_name,
        'username': buddy.user.username,
    }
    return render(request, "sport_buddies/user-detail.html", context)

 
def list_request(request):
    pengguna = Pengguna.objects.get(user=request.user)
    list_request = list(Buddy.objects.filter(user_id=pengguna, status=1)) 
    print(list_request)
    for req in list_request :
        print(req)
    context = {
        'list_request':list_request 
    }
    return render(request, 'sport_buddies/list-request.html', context)


def add_buddies(request,username_buddy):
    pengguna = Pengguna.objects.get(user=request.user)
    user_buddy = CustomUser.objects.get(username=username_buddy)
    calon_buddy = Pengguna.objects.get(user=user_buddy)
    buddy = Buddy.objects.create(
            user_id = pengguna,
            buddy_id = calon_buddy,
            status = 1
        )
    buddy.save()
    print("masuk sini")
    return redirect("/sport-buddies/user-detail/"+username_buddy)


def accept_request(request, username_buddy):
    pengguna = Pengguna.objects.get(user=request.user)
    user_calon_buddy = CustomUser.objects.get(username=username_buddy)
    calon_buddy = Pengguna.objects.get(user=user_calon_buddy)
    buddyUser = Buddy.objects.get(user_id=pengguna, buddy_id=calon_buddy)
    buddyUser.status = 3
    buddyUser.save()
    buddyReverse = Buddy.objects.create(
            user_id = calon_buddy,
            buddy_id = pengguna,
            status = 3
        )
    buddyReverse.save()
    return redirect("/sport-buddies/list-request")


def reject_request(request, username_buddy):
    pengguna = Pengguna.objects.get(user=request.user)
    user_calon_buddy = CustomUser.objects.get(username=username_buddy)
    calon_buddy = Pengguna.objects.get(user=user_calon_buddy)
    buddyUser = Buddy.objects.filter(user_id=pengguna, buddy_id=calon_buddy)
    buddyUser.status = 2
    # buddyUser.delete()
    return redirect("/sport-buddies/list-request")

def leaderboard(request):
    list_pengguna = list(Pengguna.objects.all().order_by('total_exp'))
    
    context = {
        'list_pengguna':list_pengguna 
    }
    return render(request, 'sport_buddies/leaderboard.html', context)

# def update_level(request):
#     pengguna = Pengguna.objects.get(user=request.user)
#     pengguna.level = (pengguna.total_exp // 100) + 1        #naik level tiap 100 exp, mulai dari level 1
#     pengguna.current_exp = pengguna.total_exp % 100
#     pengguna.save()

sport_buddies/templates/sport_buddies/find-sport-buddies.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}Find Sport Buddies{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

<div class="block">
    <div class="row">
        {% for pengguna in list_pengguna %}
       <a href="{% url 'sport_buddies:user-detail' pengguna.user.username %}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{pengguna.user.first_name}} {{pengguna.user.last_name}}</div>
                <div class="card-body">
                <div class="post-thumb">
                    <img src="https://cdn.discordapp.com/attachments/925303244245307432/938676562931372082/blank-profile-picture-973460_1280.png"
                        alt="post-image" class="img-fluid">
                </div>
                <p class="card-text">Username: {{pengguna.user.username}}</p>
                <p class="card-text">Jenis Kelamin: {{pengguna.get_jenis_kelamin_display}}</p>
                <p class="card-text">Level: {{pengguna.level}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock content %}

sport_buddies/templates/sport_buddies/leaderboard.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}Leaderboard{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

<div class="block">
    <div class="row">
        {% for pengguna in list_pengguna %}
       <a href="{% url 'sport_buddies:user-detail' pengguna.user.username %}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{pengguna.user.first_name}} {{pengguna.user.last_name}}</div>
                <div class="card-body">
                <div class="post-thumb">
                    <img src="https://cdn.discordapp.com/attachments/925303244245307432/938676562931372082/blank-profile-picture-973460_1280.png"
                        alt="post-image" class="img-fluid">
                </div>
                <p class="card-text">Username: {{pengguna.user.username}}</p>
                <p class="card-text">Jenis Kelamin: {{pengguna.get_jenis_kelamin_display}}</p>
                <p class="card-text">Level: {{pengguna.level}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock content %}

sport_buddies/templates/sport_buddies/list-buddies.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}Sport Buddies{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

<div class="block">
    <div class="row">
        {% for buddy in list_buddy %}
       <a href="{% url 'sport_buddies:user-detail' buddy.user.username %}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{buddy.user.first_name}} {{buddy.last_name}}</div>
                <div class="card-body">
                <div class="post-thumb">
                    <img src="https://cdn.discordapp.com/attachments/925303244245307432/938676562931372082/blank-profile-picture-973460_1280.png"
                        alt="post-image" class="img-fluid">
                </div>
                <p class="card-text">Username: {{buddy.user.username}}</p>
                <p class="card-text">Jenis Kelamin: {{buddy.get_jenis_kelamin_display}}</p>
                <p class="card-text">Level: {{buddy.level}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock content %}

sport_buddies/templates/sport_buddies/list-request.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}">
{% endblock meta %}

{% block pagename %}List Request Sport Buddies{% endblock pagename %}
{% block activehome %}nav-active{% endblock activehome %}

{% block content %}

<div class="block">
    <div class="row">
        <a class="btn btn-primary mb-2" href="/sport-buddies/">&nbsp List Sport Buddies</a>
        {% for req in list_request %}
       <a href="{% url 'sport_buddies:user-detail' req.buddy_id.user.username %}">
            <div class="card mb-3" style="max-width: 18rem;">
                <div class="card-header">{{req.buddy_id.user.first_name}} {{req.buddy_id.last_name}}</div>
                <div class="card-body">
                <div class="post-thumb">
                    <img src="https://cdn.discordapp.com/attachments/925303244245307432/938676562931372082/blank-profile-picture-973460_1280.png"
                        alt="post-image" class="img-fluid">
                </div>
                <p class="card-text">Username: {{req.buddy_id.user.username}}</p>
                <p class="card-text">Jenis Kelamin: {{req.buddy_id.get_jenis_kelamin_display}}</p>
                <p class="card-text">Level: {{req.buddy_idlevel}}</p>
                </div>
                <a class="btn btn-primary mb-2" href="{% url 'sport_buddies:accept-request' req.buddy_id.user.username %}">&nbsp Accept</a>
                <a class="btn btn-primary mb-2" href="{% url 'sport_buddies:reject-request' req.buddy_id.user.username %}">&nbsp Reject</a>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock content %}