main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("register/pengguna/", views.registrasi_pengguna, name="registrasi-pengguna"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("bantuan/", views.bantuan, name="bantuan"),
    path("pengaturan/", views.pengaturan, name="pengaturan"),
]

mobile_sporteev/urls.py
from django.contrib import admin
from django.urls import path, include

import sportivity

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('home/', include('sportivity.urls')),
    path('sportivity/', include('sportivity.urls')),
    path('profil/', include('profil.urls')),
    path('sport-buddies/', include('sport_buddies.urls')),
    path('sportwiki/', include('sportwiki.urls')),
    path('sport-venue/', include('sport_venue.urls')),
    path('admin-dashboard/', include('admin_dashboard.urls')),
]

profil/urls.py
from django.urls import path

from . import views

app_name = 'profil'

urlpatterns = [
    path("", views.profil, name="profil"),
    path("edit-profil/", views.edit_profil, name="edit-profil"),
]

sport_buddies/urls.py
from urllib import request
from django.urls import path

from . import views

app_name = 'sport_buddies'

urlpatterns = [
    path("", views.list_buddies, name="list_buddies"),
    path("list-request/", views.list_request, name="list-request"),
    path("user-detail/<str:username_buddy>", views.user_detail, name="user-detail"),
    path("add-buddies/<str:username_buddy>", views.add_buddies, name="add-buddies"),
    path("accept-request/<str:username_buddy>", views.accept_request, name="accept-request"),
    path("reject-request:/<str:username_buddy>", views.reject_request, name="reject-request"),
    path("find-sport-buddies/", views.find_sport_buddies, name="find-sport-buddies"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),

]
 

sportivity/urls.py
from django.urls import path

from . import views

app_name = 'sportivity'

urlpatterns = [
    path("", views.home_sportivity, name="home-sportivity"),
    path("buat-event-jenis/", views.buat_event_jenis, name="buat-event-jenis"),
    path("buat-event-general/", views.buat_event_general, name="buat-event-general"),
    path("buat-event-details/", views.buat_event_details, name="buat-event-details"),
    path("buat-event-checking/", views.buat_event_checking, name="buat-event-checking"),
    path("delete-event/", views.delete_event, name="delete-event"),
    path("detail-event/<int:id_event>/", views.detail_event, name="detail-event"),
    path("end-event/<int:id_event>/", views.end_event, name="end-event"),
    path("request-join/<int:id_event>/", views.request_join, name="request-join"),
    path("list-request/<int:id_event>/", views.list_request, name="list-request"),
    path("terima-request/<int:id_event_request>/", views.terima_request, name="terima-request"),
    path("tolak-request/<int:id_event_request>/", views.tolak_request, name="tolak-request"),
    path("log-aktivitas/", views.log_aktivitas, name="log-aktivitas"),
]

sportwiki/urls.py
from django.urls import path

from . import views

app_name = 'sportwiki'

urlpatterns = [
    path("", views.home_sportwiki, name="home-sportwiki"),
    path("wiki-details/", views.wiki_details, name="wiki-details"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import ModelState
from django.db.models.enums import Choices
from django_dropbox_storage.storage import DropboxStorage

# Create your models here.

class CustomUser(AbstractUser):
    is_pengguna = models.BooleanField("user status", default=False)
    is_admin = models.BooleanField(default=False)
    alamat = models.TextField(max_length=250)
    no_telepon = models.TextField(max_length=15)
    # soon bakal ada is venue


class Pengguna(models.Model):
    DROPBOX_STORAGE = DropboxStorage()
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE)
    tanggal_lahir = models.DateField()
    JENIS_KELAMIN = (
        (1, "Laki-laki"),
        (2, "Perempuan"),
    )
    jenis_kelamin = models.IntegerField(choices=JENIS_KELAMIN)
    is_active = True
    photo = models.ImageField(upload_to='photos', storage=DROPBOX_STORAGE)
    level = models.IntegerField(default=1)
    total_exp = models.IntegerField(default=0)
    current_exp = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)

# soon
# class Venue(models.Model):
#     is_active = False

class PhotoTest(models.Model):
    DROPBOX_STORAGE = DropboxStorage()
    photo = models.ImageField(upload_to='photos', storage=DROPBOX_STORAGE, blank=True, null=True, default=None)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

main/views.py
from django.db.models.query_utils import Q
from django.http import request
from django.http.response import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import redirect, render
from django.contrib import auth
from main.models import CustomUser, Pengguna
import datetime
from django.views.decorators.csrf import csrf_exempt
import json


# Create your views here.

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)

            # jika admin
            if user.is_staff:
                return redirect('/admin-dashboard')
            
            # jika bukan admin
            else:
                return redirect("/home")
        
        else:
            context = {
                'error' : 'Kredensial yang dimasukkan salah'
            }
            return render(request, 'main/login.html', context)
    
    if request.user.is_authenticated and request.user.is_active:
        return redirect("/home")
    
    return render(request, 'main/login.html')



def logout(request):
    auth.logout(request)
    return redirect("/")


def register(request):
    if request.method == "POST":
        register_type = request.POST["register_type"]
        nama_belakang = request.POST["nama_belakang"]
        nama_depan = request.POST["nama_depan"]
        username = request.POST["username"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        alamat = request.POST["alamat"]
        no_telepon = request.POST["no_telepon"]
        email = request.POST["email"]

        if register_type == "pengguna":
            tanggal_lahir = request.POST["tanggal_lahir"]
            jenis_kelamin = request.POST["jenis_kelamin"]
        
        # soon
        # elif register_type == "venue" :
        #     jenis_venue =
            
        try:
            user = CustomUser.objects.get(username=username)
            if user is not None:
                context = {
                    "error":"User dengan username atau email tersebut sudah terdaftar"
                }
                if register_type == "pengguna":
                    # return render(request, "sportivity/list-event.html", context)
                    return redirect("/home")

                # soon
                # return render(request, "main/register-venue.html", context)
        
        except CustomUser.DoesNotExist:
            user = CustomUser(
                username = username,
                first_name = nama_depan,
                last_name = nama_belakang,
                email = email,
                alamat = alamat,
                no_telepon = no_telepon
            )
            user.set_password(password1)
            
            if register_type == "pengguna":
                pengguna = Pengguna()
                user.is_active = True
                user.is_pengguna = True
                # user.is_venue = False
                pengguna.user = user
                pengguna.tanggal_lahir = tanggal_lahir
                pengguna.jenis_kelamin = jenis_kelamin
                user.save()
                pengguna.save()
                user = auth.authenticate(request, username=username, password=password1)
                auth.login(request, user)
                return redirect("/home")

            # soon
            # elif register_type == "venue":
            #     user.is_active = False


    if request.user.is_authenticated and request.user.is_active:
        return redirect("/home")
    
    return render(request, "main/register-home.html")

            
def registrasi_pengguna(request):
    return render(request, "main/registrasi-pengguna.html")

def about(request):
    return render(request, "main/about.html")

def faq(request):
    return render(request, "main/faq.html")

def bantuan(request):
    return render(request, "main/bantuan.html")

def pengaturan(request):
    return render(request, "main/pengaturan.html")

# soon
# def registrasi_venue(request):
#     return blablabla

# soon
# def check_venue(request):
#     nanti

main/templates/main/about.html
ini about

main/templates/main/bantuan.html
ini Bantuan

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <!-- Font Awesome CDN -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

  <!-- Remix Icon CDN -->
  <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}" />

  <!-- Font Poppins -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

  <!-- Styling for specific pages -->
  {% block meta %}
  {% endblock meta %}

  <!-- Main style for parent page -->
  <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>

  <title>Sporteev</title>
</head>

<body>

  <!-- Header -->
  <header class="p-3 text-white sticky-top">
    <div class="container-fluid">
      <div class="d-flex justify-content-between" style="align-items: center;">
        <div class="col-1 d-flex justify-content-center">
          <a href="#" class="menu-bars" id="show-menu-left">
            <i class="fas fa-bars icon-header"></i>
          </a>
        </div>
        <nav id="nav-menu-left">
          <ul class="px-3 pt-0 nav-menu-items">
            <div class="py-4 navbar-toggle">
              <a href="#" class="menu-bars" id="hide-menu-left">
                <i class="fas fa-bars nav-icon"></i>
              </a>
              <p> Menu</p>
            </div>
            <hr />
            <div class="nav-section my-3">
              <li class="nav-text"><a href="{% url 'profil:profil' %}"><i class="far fa-user-circle nav-icon"></i>Akun</a></li>
              <li class="nav-text"><a href="{% url 'sport_buddies:list_buddies' %}"><i class="fas fa-user-plus nav-icon"></i>Sport Buddies</a></li>
              <li class="nav-text"><a href="{% url 'sport_buddies:leaderboard' %}"><i class="fas fa-trophy nav-icon"></i>Leaderboard</a></li>
              <li class="nav-text"><a href="{% url 'sportwiki:home-sportwiki' %}"><i class="fas fa-book-open nav-icon"></i>SportWiki</a></li>
              <li class="nav-text"><a href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt nav-icon"></i>Log out</a></li>
            </div>
            <hr />
            <div class="nav-section my-1">
              <li class="nav-text"><a href="{% url 'main:bantuan' %}"><i class="fas fa-question nav-icon"></i>Bantuan</a></li>
              <li class="nav-text"><a href="{% url 'main:pengaturan' %}"><i class="fas fa-cog nav-icon"></i>Pengaturan</a></li>
              <li class="nav-text"><a href="{% url 'main:about' %}"><i class="far fa-exclamation-circle nav-icon"></i>Tentang Sporteev</a></li>
            </div>
          </ul>
        </nav>
        <div class="col-6 d-flex justify-content-center">
          {% block pagename %}{% endblock pagename %}
        </div>
        <div class="col-1 d-flex justify-content-center">
          <a href="#" class="menu-bars" id="show-menu-right">
            <i class="far fa-bell icon-header"></i>
          </a>
        </div>
        <nav id="nav-menu-right">
          <ul class="px-3 pt-0 nav-menu-items">
            <div class="p-4 navbar-toggle right">
              <p>Notifikasi </p>
              <a href="#" class="menu-bars" id="hide-menu-right">
                <i class="far fa-bell nav-icon right"></i>
              </a>
            </div>
            <hr />
            <div class="nav-section my-1">
              <li class="nav-text"><a href="#">Ini contoh</a></li>
              <li class="nav-text"><a href="#">Ini juga contoh</a></li>
              <li class="nav-text"><a href="#">Sama, ini contoh juga</a></li>
            </div>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <div id="hide-menu">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- Navbar -->
  <footer class="footer mt-auto bg-light">
    <nav class="navbar navbar-expand-md navbar-dark fixed-bottom bg-light app-footer">
      <div class="container-fluid d-flex flex-row justify-content-around text-black font-footer text-center">
        <a class="navi-text" href="/sportivity">
          <div class="px-2 bd-highlight {% block activehome %}{% endblock activehome %}">
            <i class="ri-home-line icon-footer"><br></i>
            Home
          </div>
        </a>
        <a class="navi-text" href="/sport-venue/list-venue">
          <div class="px-2 py-1 bd-highlight {% block activevenue %}{% endblock activevenue %}">
            <i class="ri-map-pin-5-line icon-footer"><br></i>
            Venue
          </div>
        </a>
        <a class="navi-text" href="/sportivity/buat-event-jenis">
          <div class="px-2 bd-highlight {% block activebuat %}{% endblock activebuat %}">
            <i class="ri-add-circle-line icon-footer" style="font-size: 25px"><br></i>
            Buat
          </div>
        </a>
        <a class="navi-text" href="{% url 'sportivity:log-aktivitas' %}">
          <div class="px-1 bd-highlight {% block activelog %}{% endblock activelog %}">
            <i class="ri-history-line icon-footer"><br></i>
            Aktivitas
          </div>
        </a>
        <a class="navi-text" href="/profil">
          <div class="px-2 bd-highlight {% block activeprofile %}{% endblock activeprofile %}">
            <i class="ri-user-line icon-footer"><br></i>
            Profil
          </div>
        </a>
      </div>
    </nav>
  </footer>

  <!-- Fake Navbar -->
  <nav class="navbar-dark bg-white sticky-bottom" style="box-shadow: unset;"></nav>

  <script src="{% static 'js/base.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

main/templates/main/faq.html
ini faq

main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->

{% endblock meta %}

{% block pagename %}Login{% endblock pagename %}
{% comment %} {% block activehome %}nav-active{% endblock activehome %} {% endcomment %}

{% block content %}

<section class="section contact-form py-5 my-0">
    <div class="container col-sm-8 col-md-6 col-lg-4">
        <div class="row">
            <div class="col-12 text-center login">
                <img src="{% static 'img/logo1.png' %}" alt="logo">
                <div class="section-title">
                    <h3 style="font-size: 180%; margin-bottom: 3%;">Login</span></h3>
                    <p>to continue to Sporteev</p>
                </div>
            </div>
        </div>
        <form id="frm" method="POST" action="/" class="row">
            {% csrf_token %}
            <div class="col-md-12">
                <input required type="text" class="form-control main" name="username" id="username"
                    placeholder="Username">
            </div>
            <div class="col-md-12">
                <input type="password" class="form-control main" name="password" id="password" placeholder="Password">
            </div>
            <div class="col-sm-6 px-0 mb-4 belum-daftar" style="font-size: small;">
                <p class="col-10 col-lg-12">Belum punya akun?</p>
                <a href="/register" style="text-decoration: none;"><h6 class="col-10 col-lg-12 signup-btn" style="font-size: medium;">Sign up</h6></a>
            </div>
            <div class="col-12 col-sm-6 text-center belum-daftar2">
                <button type="submit" class="btn btn-main-md my-0">Login</button>
                <div class="error-message w-100 mt-2">
                    <p style="color:red">{{error}}</p>
                </div>
            </div>
        </form>
    </div>
</section>

{% comment %} <div class="container d-flex flex-column align-items-center justify-content-center">
    <img class="login-image" src="">
    <div class="tulisan-login mt-5">
        Login
    </div>
    <form id="frm" method="POST" action="/">
        {% csrf_token %}
        <div class="mb-3 mt-4">
            <label for="username" class="form-label">Username</label>
            <input required name="username" type="text" class="form-control" id="username">
        </div>
        <div class="mb-3 mt-2">
            <label for="password" class="form-label">Password</label>
            <input required name="password" type="password" class="form-control" id="password">
        </div>
        <button id="submit" type="submit" class="btn btn-success w-100 mt-4" value="submit">Login</button>
        <div class="error-message w-100 mt-2">
            <p style="color:red">{{error}}</p>
        </div>
    </form>
    <div style="width:75%; text-align:center;" class="mt-5 mb-5">
        <span>Belum mempunya akun?</span> <a href="/register" class="daftar-button">Daftar sekarang!</a>
    </div>
</div> {% endcomment %}
{% comment %}
<script src="{% static 'js/login.js'%}"></script> {% endcomment %}
{% endblock content %}

main/templates/main/navbar-with-title.html
{% load static %}
<div class="navbar-container d-flex justify-content-between">
    <div class="arrow-left">
        <a href="{{linkback}}">
        <!-- <button onclick=""> -->
            <img src="{% static 'main/img/arrow.png' %}" alt="">
        </a>
    </div>
    <div >
        <span class="title">{{title}}</span>
    </div>
    {% if linksimpan is not None %}
    <!-- <a href="{{linksimpan}}"> -->
    <!-- <button onclick={{onclick}}> -->
    <div>
        <button onclick="{{onclick}}" style="background-color: #EF233C !important;" type="button" class="btn btn-danger btn-simpan">Simpan</button>
    </div>
    <!-- </button> -->
    {% endif %}

    {% if linklogout is not None %}
    <div >
        <a href="{{linklogout}}" type="button" class="btn btn btn-outline-danger">Logout</a>
    </div>
    {% endif %}
</div>

main/templates/main/pengaturan.html
ini Pengaturan

main/templates/main/profil-ngungsi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>

  <title>Sporteev</title>
  {% block meta %}
  {% endblock meta %}

</head>

<body>
  <div id="splash">
    <img src="{% static 'img/sporteev-logo.png' %}" alt="" class="logo">
  </div>

  <div class="content">
    <header class="app-header">
      <div class="container">
        <img src="{% static 'img/sporteev-logo-cropped.png' %}" alt="" class="logo">
        <input type="text" class="search" placeholder="Cari...">
      </div>
    </header>

    <div class="subheader">
      <div>
        <p>Halo! <br>
          Olahraga apa hari ini? <i class="fas fa-angle-right"></i></p>
      </div>
      <div>
        <img src="{% static 'img/venue.png' %}" alt="" class="">
      </div>
    </div>

    <div class="grid container">
      <div class="item">
        <h4>Sportivity</h4>
        <p>Find Sport buddies</p>
        <img src="{% static 'img/user.png' %}" alt="">
      </div>
      <div class="item">
        <h4>Sportivity</h4>
        <p>Find Sport buddies</p>
        <img src="{% static 'img/user.png' %}" alt="">
      </div>
      <div class="item">
        <h4>Sportivity</h4>
        <p>Find Sport buddies</p>
        <img src="{% static 'img/user.png' %}" alt="">
      </div>
      <div class="item">
        <h4>Sportivity</h4>
        <p>Find Sport buddies</p>
        <img src="{% static 'img/user.png' %}" alt="">
      </div>
      <div class="item">
        <h4>Sportivity</h4>
        <p>Find Sport buddies</p>
        <img src="{% static 'img/user.png' %}" alt="">
      </div>
      <div class="item">
        <h4>Sportivity</h4>
        <p>Find Sport buddies</p>
        <img src="{% static 'img/user.png' %}" alt="">
      </div>
    </div>
  </div>

  <footer class="app-footer">
    <ul>
      <li>
        <i class="fas fa-baseball-ball"></i>
        Home
      </li>
      <li>
        <i class="fas fa-baseball-ball"></i>
        Home
      </li>
      <li>
        <i class="fas fa-baseball-ball"></i>
        Home
      </li>
      <li>
        <i class="fas fa-baseball-ball"></i>
        Home
      </li>
      <li>
        <i class="fas fa-baseball-ball"></i>
        Home
      </li>
    </ul>
  </footer>

  <script>
    setTimeout(() => {
      document.getElementById('splash').classList.add('fade');
    }, 2000);
  </script>

</body>

</html>

main/templates/main/register-home.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock meta %}

{% block content %}
<div class="container d-flex flex-column align-items-center">
    <img class="register-image" src="{% static 'img/sporteev-logo.png' %}">
    <div class="judul">
        <p class="register">Register</p>
        <p class="heading2">Anda ingin mendaftar sebagai...</p>
    </div>
    <div class="role d-flex">
        <div class="card">
            <img src="{% static 'img/user.png' %}">
            <p class="user-role">Pengguna</p>
            <p class="deskripsi">
                Pengguna bisa mencari teman berolahraga dan mencari venue
            </p>
            <a href="/register/pengguna" class="btn btn-success">Register</a>
        </div>
        <div class="card">
            <img src="{% static 'img/venue.png' %}">
            <p class="user-role">Venue</p>
            <p class="deskripsi">
                Venue bisa mengelola venuenya
            </p>
            <a href="#" class="btn btn-danger">Soon</a>
        </div>
    </div>
    <p class="mt-5 login">
        Sudah mempunyai akun? <a href="/">Login sekarang!</a>
    </p>
</div>

{% endblock content %}

main/templates/main/registrasi-pengguna.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/register-pengguna.css' %}" with linkback="/">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock meta%}
  
{% block content %}

<div class="container d-flex flex-column align-items-center justify-content-center form-re">
    <div class="tulisan-login mt-4 mb-3">
        Register sebagai <span class="red">pengguna</span>
    </div>
    <form method="POST" action="/register/">
      {% csrf_token %}
          {% if error is not None %}
          <div class="error-message w-100">
            <p style="color:var(--primary-accent-color)">{{error}}</p>
          </div>
          {% endif %}
          <div class="mb-3 mt-4"> 
            <label for="nama_depan" class="form-label">Nama depan</label>
            <input required name="nama_depan" type="text" class="form-control" id="nama_depan">
          </div>
          <div class="mb-3 mt-4"> 
            <label for="nama_belakang" class="form-label">Nama belakang</label>
            <input required name="nama_belakang" type="text" class="form-control" id="nama_belakang">
          </div>
          <div class="mb-3 mt-2">
            <label for="jeniskelamin" class="form-label">Jenis Kelamin</label>
            <select required class="form-select" name="jenis_kelamin">
              <option value="1">Laki-Laki</option>
              <option value="2">Perempuan</option>
            </select>
          </div>
          <div class="mb-3 mt-2">
            <label for="tanggal_lahir" class="form-label">Tanggal lahir</label>
            <input required name="tanggal_lahir" type="date" class="form-control" id="tanggal_lahir">
          </div>
          <div class="mb-3 mt-2">
            <label for="username" class="form-label">Username</label>
            <input required name="username" type="text" class="form-control" id="username">
          </div>
          <div class="mb-3 mt-2">
            <label for="email" class="form-label">Email</label>
            <input required name="email" type="email" class="form-control" id="email">
          </div>
          <div class="mb-3 mt-2">
            <label for="password" class="form-label">Password</label>
            <input required name="password1" type="password" class="form-control" id="password">
          </div>
          <div class="mb-3 mt-2">
            <label for="ulangi-password" class="form-label">Ulangi Password</label>
            <input required onkeyup="passwordValidation()" name="password2" type="password" class="form-control" id="ulangi-password">
          </div>
          <div class="mb-3 mt-2">
            <label for="alamat" class="form-label">Alamat</label>
            <textarea required name="alamat" class="form-control" id="alamat"></textarea>
          </div>
          <div class="mb-3 mt-2">
            <label for="notelp" class="form-label">No Telepon</label>
            <input required name="no_telepon" class="form-control" id="notelp">
          </div>
          <input type="hidden" value="pengguna" name="register_type">
        <button id="button-submit" type="submit" class="btn btn-danger w-100 mt-4" value="submit">Register</button>
    </form>
</div>

{% comment %} <script src="{%static 'js/register.js'%}"></script> {% endcomment %}
{% endblock content %} 