main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path("", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("register/pengguna/", views.registrasi_pengguna, name="registrasi-pengguna"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("bantuan/", views.bantuan, name="bantuan"),
    path("pengaturan/", views.pengaturan, name="pengaturan"),
]

mobile_sporteev/urls.py
from django.contrib import admin
from django.urls import path, include

import sportivity

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('home/', include('sportivity.urls')),
    path('sportivity/', include('sportivity.urls')),
    path('profil/', include('profil.urls')),
    path('sport-buddies/', include('sport_buddies.urls')),
    path('sportwiki/', include('sportwiki.urls')),
    path('sport-venue/', include('sport_venue.urls')),
    path('admin-dashboard/', include('admin_dashboard.urls')),
]

sportivity/urls.py
from django.urls import path

from . import views

app_name = 'sportivity'

urlpatterns = [
    path("", views.home_sportivity, name="home-sportivity"),
    path("buat-event-jenis/", views.buat_event_jenis, name="buat-event-jenis"),
    path("buat-event-general/", views.buat_event_general, name="buat-event-general"),
    path("buat-event-details/", views.buat_event_details, name="buat-event-details"),
    path("buat-event-checking/", views.buat_event_checking, name="buat-event-checking"),
    path("delete-event/", views.delete_event, name="delete-event"),
    path("detail-event/<int:id_event>/", views.detail_event, name="detail-event"),
    path("end-event/<int:id_event>/", views.end_event, name="end-event"),
    path("request-join/<int:id_event>/", views.request_join, name="request-join"),
    path("list-request/<int:id_event>/", views.list_request, name="list-request"),
    path("terima-request/<int:id_event_request>/", views.terima_request, name="terima-request"),
    path("tolak-request/<int:id_event_request>/", views.tolak_request, name="tolak-request"),
    path("log-aktivitas/", views.log_aktivitas, name="log-aktivitas"),
]

sportivity/models.py
from typing import Callable
from django.db import models
from django.db.models.deletion import CASCADE
from main.models import Pengguna
from django_dropbox_storage.storage import DropboxStorage
# from location_field.models.plain import PlainLocationField
from django.db.models.fields.related import ManyToManyField


# Create your models here.

# class Place(models.Model):
#     city = models.CharField(max_length=255)
#     location = PlainLocationField(based_fields=['city'], zoom=7)

class Event(models.Model):
    DROPBOX_STORAGE = DropboxStorage()
    nama_event = models.CharField(max_length=50, null=True)
    host = models.ForeignKey(Pengguna, on_delete=CASCADE, blank=False, null=True)
    tanggal = models.DateField(auto_now=False, auto_now_add=False, null=True)
    waktu_start = models.TimeField(auto_now=False, auto_now_add=False, null=True)
    waktu_end = models.TimeField(auto_now=False, auto_now_add=False,null=True)
    # venue = models.ForeignKey(Venue, on_delete=CASCADE, blank=False)
    venue = models.CharField(max_length=50, blank=False, null=True)
    alamat = models.CharField(max_length=100, blank=False, null=True)
    harga = models.IntegerField(default=0, null=True)
    JENIS_OLAHRAGA = (
        (1, "Badminton"),
        (2, "Sepak bola"),
        (3, "Basket"),
        (4, "Voli"),
        (5, "Tenis"),
        (6, "Tenis Meja"),
        (7, "Baseball"),
        (8, "Bersepeda"),
        (9, "Lari"),
        (10, "Other"),
    )    
    jenis_olahraga = models.IntegerField(choices=JENIS_OLAHRAGA, default=1, null=True)
    LEVEL = (
        (0, "All Level"),
        (1, "Rookie"),
        (2, "Beginner"),
        (3, "Intermediete"),
        (4, "Advanced"),
        (5, "Expert"),
    )
    level = models.IntegerField(choices=LEVEL, default=0, null=True)
    min_participant = models.IntegerField(null=True)
    max_participant = models.IntegerField(null=True)
    current_participant = models.IntegerField(default=1 ,null=True)
    deskripsi = models.TextField(null=True)
    is_ranked = models.BooleanField(default=False, null=True)
    is_private = models.BooleanField(default=False, null=True)
    photo = models.ImageField(upload_to='photos', storage=DROPBOX_STORAGE, null=True)
    STATUS = (
        (0, "Draft"),
        (1, "Upcoming"),
        (2, "Ongoing"),
        (3, "Finished"),
        (4, "Cancelled")
    )
    status = models.IntegerField(choices=STATUS, default=0, null=True)


class EventRequest(models.Model):
    event_id = models.ForeignKey(Event, on_delete=CASCADE, blank=False)
    participant = models.ForeignKey(Pengguna, on_delete=CASCADE, blank=False)
    STATUS_REQUEST = (
        (0, "Draft"),
        (1, "Menunggu Konfirmasi"),
        (2, "Diterima"),
        (3, "Ditolak"),
        (4, "Selesai")
    )
    status_request = models.IntegerField(choices=STATUS_REQUEST, default=0)
    

sportivity/views.py
from django.http import request
from django.shortcuts import redirect, render, resolve_url
from main.models import Pengguna
from django.views.decorators.csrf import csrf_exempt
from sportivity.models import Event, EventRequest
from profil.views import update_level
import string
import random

# Create your views here.

alpha_numeric = string.ascii_uppercase + string.digits
#generate random string
def id_generator(size=6, chars=alpha_numeric):
    return ''.join(random.choice(chars) for _ in range(size))

def home_sportivity(request):
    list_event = list(Event.objects.filter(status=1))
    context = {
        'list_event' : list_event
    }
    print(list_event)
    return render(request, 'sportivity/list-event.html', context)


def buat_event_jenis(request):
    if request.method == "POST":
        pengguna = Pengguna.objects.get(user=request.user)
        jenis_olahraga = request.POST["jenis_olahraga"]
        event = Event.objects.create(
            jenis_olahraga = jenis_olahraga,
            host = pengguna
        )
        return redirect("/sportivity/buat-event-general/")

    return render(request, 'sportivity/buat-event-jenis.html')

def buat_event_general(request):
    if request.method == "POST":
        pengguna = Pengguna.objects.get(user=request.user)
        list_event = list(Event.objects.filter(host=pengguna))
        event = list_event[-1]
        event.nama_event = request.POST["nama_event"]
        event.deskripsi = request.POST["deskripsi"]
        event.tanggal = request.POST["tanggal"]
        event.waktu_start = request.POST["waktu_start"]
        event.waktu_end = request.POST["waktu_end"]
        event.venue = request.POST["venue"]
        event.alamat = request.POST["alamat"]
        # if request.FILES.get('myfile',False):
        #         new_foto = request.FILES['myfile']

        #         foto_format = "." + ((new_foto.name).split("."))[-1]
        #         new_foto_name = (new_foto.name).replace(foto_format,"")
        #         if pengguna.photo.name != "":
        #             prev_foto_name = ((pengguna.photo.name).split(".")[0])[15:]
        #         else:
        #             prev_foto_name = alpha_numeric
        #         # (petunjuk) new foto name <-- rand(new_foto) + rand(prev_foto) + rand(string) + file formats
        #         new_foto.name = id_generator(6,new_foto_name) + id_generator(6,prev_foto_name) + id_generator() + foto_format

        #         event.photo = new_foto
        event.save()
        return redirect("/sportivity/buat-event-details/")

    return render(request, 'sportivity/buat-event-general.html')


def buat_event_details(request):
    if request.method == "POST":
        pengguna = Pengguna.objects.get(user=request.user)
        list_event = list(Event.objects.filter(host=pengguna))
        event = list_event[-1]
        event.min_participant = request.POST["min_participant"]
        event.max_participant = request.POST["max_participant"]
        event.harga = request.POST["harga"]
        event.level = request.POST["level"]
        # status_is_ranked = request.POST["is_ranked"]
        # status_is_private = request.POST["is_private"]
        # if status_is_ranked == "on":
        #      event.is_ranked = True
        # if status_is_private == "on":
        #      event.is_private = True
        event.save()
        return redirect("/sportivity/buat-event-checking/")

    return render(request, 'sportivity/buat-event-details.html')


def buat_event_checking(request):
    if request.method == "POST":
        pengguna = Pengguna.objects.get(user=request.user)
        list_event = list(Event.objects.filter(host=pengguna))
        event = list_event[-1]
        event.status = 1
        print(event.status)
        update_level(request)
        event.save()
        return redirect("/home")
    
    pengguna = Pengguna.objects.get(user=request.user)
    list_event = list(Event.objects.filter(host=pengguna))
    event = list_event[-1]
    nama_event = event.nama_event
    host = event.host
    deskripsi = event.deskripsi
    tanggal = event.tanggal
    waktu_start = event.waktu_start
    waktu_end = event.waktu_end
    venue = event.venue
    alamat = event.alamat
    min_participant = event.min_participant
    max_participant = event.max_participant
    harga = event.harga
    level = event.level

    context = {
        'nama_event':nama_event,
        'host':host,
        'deskripsi':deskripsi,
        'tanggal':tanggal,
        'waktu_start':waktu_start,
        'waktu_end':waktu_end,
        'venue':venue,
        'alamat':alamat,
        'min_participant':min_participant,
        'max_participant':max_participant,
        'harga':harga,
        'level':level
    }
    return render(request, 'sportivity/buat-event-checking.html', context)

def delete_event(request):
    pengguna = Pengguna.objects.get(user=request.user)
    list_event = list(Event.objects.filter(host=pengguna))
    event = list_event[-1]
    event.delete()
    return redirect("/sportivity/buat-event-jenis/")



def detail_event(request, id_event):
    pengguna = Pengguna.objects.get(user=request.user)
    tmp_event = Event.objects.filter(id=id_event)
    event = tmp_event[0]
    print(event)
    id_event = event.id
    nama_event = event.nama_event
    host = event.host
    deskripsi = event.deskripsi
    tanggal = event.tanggal
    waktu_start = event.waktu_start
    waktu_end = event.waktu_end
    venue = event.venue
    alamat = event.alamat
    min_participant = event.min_participant
    max_participant = event.max_participant
    harga = event.harga
    level = event.level
    jenis_olahraga = event.jenis_olahraga

    context = {
        'id_event' : id_event,
        'nama_event':nama_event,
        'host':host,
        'deskripsi':deskripsi,
        'tanggal':tanggal,
        'waktu_start':waktu_start,
        'waktu_end':waktu_end,
        'venue':venue,
        'alamat':alamat,
        'min_participant':min_participant,
        'max_participant':max_participant,
        'harga':harga,
        'level':level,
        'pengguna':pengguna,
        'jenis_olahraga':jenis_olahraga,
    }
    return render(request, 'sportivity/detail-event.html', context)


def request_join(request, id_event):
    if request.method == "POST":
        pengguna = Pengguna.objects.get(user=request.user)
        event_id = Event.objects.get(id=id_event)
    
        event_request = EventRequest.objects.create(
                event_id = event_id,
                participant = pengguna,
                status_request = 1
        )
        return redirect("/home/")

def list_request(request, id_event):
    list_event_request = list(EventRequest.objects.filter(event_id=id_event))
    context = {
        'list_event_request' : list_event_request,
        'id_event' : id_event
    }
    return render(request, 'sportivity/list-request.html', context)

def terima_request(request, id_event_request):
    if request.method == "POST":
        id_event = request.POST["id_event"]
        event_request = EventRequest.objects.get(id=id_event_request)
        event = Event.objects.get(id=event_request.event_id.id)
        event.current_participant += 1
        event_request.status_request = 2
        event.save()
        event_request.save()
        return redirect("/sportivity/list-request/"+id_event)

def tolak_request(request, id_event_request):
    if request.method == "POST":
        id_event = request.POST["id_event"]
        event_request = EventRequest.objects.get(id=id_event_request)
        event_request.status_request = 3
        event_request.save()
        return redirect("/sportivity/list-request/"+id_event)

def end_event(request, id_event):
    if request.method == "POST":
        event = Event.objects.get(id=id_event)
        event.status = 2                        # set status jadi selesai
        list_event_request = list(EventRequest.objects.filter(event_id=event))
        for event_request in list_event_request :
            event_request.status = 4            # set status jadi selesai
            peserta = event_request.participant
            peserta.total_exp += 10
            peserta.save()
            event_request.save()
        event.save()
        return redirect("/sportivity/")

def log_aktivitas(request):
    if request.method == "GET":
        pengguna = Pengguna.objects.get(user=request.user)
        list_event_host = list(Event.objects.filter(host=pengguna))
        list_event_request = list(EventRequest.objects.filter(participant=pengguna))
        list_event = []
        for event_request in list_event_request :
            list_event.append(event_request.event_id)

        for event_host in list_event_host :
            list_event.append(event_host)

        context = {
        'list_event' : list_event
        }
        print(list_event)
        
        return render(request, 'sportivity/log-aktivitas.html', context)

sportivity/templates/sportivity/buat-event-checking.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/register-pengguna.css' %}" with linkback="/">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% endblock meta%}

{% block pagename %}Buat Aktivitas{% endblock pagename %}
{% block activebuat %}nav-active{% endblock activebuat %}
  
{% block content %}
<div class="container d-flex flex-column align-items-center justify-content-center form-re">
    <div class="tulisan-login mt-4 mb-3">
        Checking
    </div>
    <h4>Activity Name: {{nama_event}}</h4>
    <h4>Host: {{host}}</h4>
    <h4>Deskripsi: {{deskripsi}}</h4>
    <h4>Tanggal: {{tanggal}}</h4>
    <h4>Waktu: {{waktu_start}} - {{waktu_end}}</h4>
    <h4>Min-Max Player: {{min_participant}}-{{max_participant}} players</h4>
    <h4>Harga: Rp{{harga}}/orang</h4>
    <h4>Level: {{level}}</h4>
    <form method="POST" action="{% url 'sportivity:buat-event-checking' %}">
      {% csrf_token %}
      <button id="button-submit" type="submit" class="btn btn-success w-100 mt-4" value="submit">Buat Event</button>
      <input type=button value="Previous Page" class="btn btn-danger w-100 mt-4" onClick="javascript:history.go(-1);">
    </form>
    
</div>

{% endblock content %} 

sportivity/templates/sportivity/buat-event-general.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
{% comment %}
<link rel="stylesheet" href="{% static 'css/list-event.css'%}"> {% endcomment %}
{% endblock meta %}

{% block pagename %}Buat Aktivitas{% endblock pagename %}
{% block activebuat %}nav-active{% endblock activebuat %}

{% block content %}

<section class="registration">
  <div class="container-fuild p-0">
    <div class="row">
      <div class="col-lg-12 col-md-12 p-0">
        <div class="registration-block bg-registration overlay-dark py-5 mb-5">
          <div class="block">
            <div class="title text-left">
              <h3>Informasi <span class="alternate">General</span></h3>
              <p>aktivitas olahraga</p>
            </div>
            <form method="POST" action="{% url 'sportivity:buat-event-general' %}" class="row">
              {% csrf_token %}
              <div class="col-md-6">
                <label for="nama_event" class="form-label">Nama Aktivitas</label>
                <input required name="nama_event" type="text" class="form-control main border-white placeholder-white" placeholder="Nama Aktivitas" id="nama_event">
              </div>
              {% comment %} <div class="col-md-6">
                <label for="nama_event" class="form-label">Foto</label>
                <input type="file" id="imageFileInput" class="input-picture" accept="image/png, image/jpeg" name="myfile">
              </div> {% endcomment %}
              <div class="col-md-6">
                <label for="deskripsi" class="form-label">Deskripsi (opsional)</label>
                <input name="deskripsi" type="textarea" class="form-control main border-white placeholder-white" placeholder="Deskripsi" id="deskripsi">
              </div>
              <div class="col-md-6">
                <label for="venue" class="form-label">Tempat</label>
                <input required name="venue" type="text" class="form-control main border-white placeholder-white" placeholder="Tempat" id="venue">
              </div>
              <div class="col-md-6">
                <label for="tanggal" class="form-label">Tanggal</label>
                <input required name="tanggal" type="date" class="form-control main border-white placeholder-white" placeholder="Tanggal" id="tanggal">
              </div>
              <div class="col-md-6">
                <label for="waktu_start" class="form-label">Waktu mulai</label>
                <input required name="waktu_start" type="time" class="form-control main border-white placeholder-white" placeholder="Waktu Mulai" id="waktu_start">
              </div>
              <div class="col-md-6">
                <label for="waktu_end" class="form-label">Waktu selesai</label>
                <input required name="waktu_end" type="time" class="form-control main border-white placeholder-white" placeholder="Waktu Selesai" id="waktu_end">
              </div>
              <div class="col-md-6">
                <label for="alamat" class="form-label">Alamat (opsional)</label>
                <input name="alamat" type="text" class="form-control main border-white placeholder-white" placeholder="Alamat" id="alamat">
              </div>
              {% comment %} <div class="col-md-6">
                <div class="form-group">
                  <select class="form-control main" id="select-ticket">
                    <option>Ticket Type</option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                </div>
              </div> {% endcomment %}
              <div class="col-12">
                <button type="submit" class="btn btn-white-md">Selanjutnya</button>
              </div>
            </form>
            <form method="POST" action="{% url 'sportivity:delete-event' %}">
              {% csrf_token %}
              <div class="col-12 mt-3">
                <button id="button-submit" type="submit" class="btn btn-danger" value="submit">Batal</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<br>

{% comment %} <div class="container d-flex flex-column align-items-center justify-content-center form-re">
  <div class="tulisan-login mt-4 mb-3">
    General
  </div>
  <form method="POST" action="{% url 'sportivity:buat-event-general' %}">
    {% csrf_token %}
    <div class="mb-3 mt-4">
      <label for="nama_event" class="form-label">Nama Aktivitas</label>
      <input required name="nama_event" type="text" class="form-control" id="nama_event">
    </div>
    <div class="mb-3 mt-4">
      <label for="deskripsi" class="form-label">Deskripsi</label>
      <input required name="deskripsi" type="textarea" class="form-control" id="deskripsi">
    </div>
    <div class="mb-3 mt-2">
      <label for="tanggal" class="form-label">Tanggal</label>
      <input required name="tanggal" type="date" class="form-control" id="tanggal">
    </div>
    <div class="mb-3 mt-2">
      <label for="waktu_start" class="form-label">Start</label>
      <input required name="waktu_start" type="time" class="form-control" id="waktu_start">
    </div>
    <div class="mb-3 mt-2">
      <label for="waktu_end" class="form-label">End</label>
      <input required name="waktu_end" type="time" class="form-control" id="waktu_end">
    </div>
    <div class="mb-3 mt-2">
      <label for="venue" class="form-label">Venue</label>
      <input required name="venue" type="text" class="form-control" id="venue">
    </div>
    <div class="mb-3 mt-2">
      <label for="alamat" class="form-label">Alamat</label>
      <input required name="alamat" type="text" class="form-control" id="alamat">
    </div>
    <button id="button-submit" type="submit" class="btn btn-success w-100 mt-4" value="submit">Next</button>
  </form>
  <form method="POST" action="{% url 'sportivity:delete-event' %}">
    {% csrf_token %}
    <button id="button-submit" type="submit" class="btn btn-danger w-100 mt-4 px-auto mx-auto"
      value="submit">Cancel</button>
  </form>
  <br><br><br><br><br>
</div> {% endcomment %}

{% comment %}
<script src="{%static 'js/register.js'%}"></script> {% endcomment %}



{% endblock content %}

sportivity/templates/sportivity/log-aktivitas.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta %}
<!-- ========== Start Eventre Templates Head ========== -->

<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- PLUGINS CSS STYLE -->
<!-- Bootstrap -->
<link href="{% static 'assets-eventre/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome -->
<link href="{% static 'assets-eventre/plugins/font-awsome/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Magnific Popup -->
<link href="{% static 'assets-eventre/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
<!-- Slick Carousel -->
<link href="{% static 'assets-eventre/plugins/slick/slick.css' %}" rel="stylesheet">
<link href="{% static 'assets-eventre/plugins/slick/slick-theme.css' %}" rel="stylesheet">
<!-- CUSTOM CSS -->
<link href="{% static 'assets-eventre/css/style.css' %}" rel="stylesheet">

<!-- ========== End Eventre Templates Head ========== -->
{% comment %}
<link rel="stylesheet" href="{% static 'css/profil.css'%}"> {% endcomment %}
<!-- <link rel="stylesheet" href="{% static 'css/list-event.css'%}"> -->
{% endblock meta %}

{% block pagename %}Aktivitas Saya{% endblock pagename %}
{% block activelog %}nav-active{% endblock activelog %}

{% block content %}

<section class="news-hr section mb-0">
	<div class="container px-2">
		<div class="">
			<div class="col-12">
				<div class="text-center mx-5 mt-4 mb-5">
					<h3>Log <span class="alternate">Aktivitas</span></h3>
					<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, enim.</p> -->
				</div>
			</div>
		</div>
		<div class="row no-gutters">
			{% for event in list_event %}
			<div class="col-md-6 p-2">
				<article class="news-post-hr">
					<div class="post-thumb">
						<a href="{% url 'sportivity:detail-event' event.id %}">
							<img src="{% static 'assets-eventre/images/news/bcf.png' %}" alt="post-image"
								class="img-fluid">
						</a>
					</div>
					<div class="post-contents border-top">
						<div class="post-title text-start">
							<h6 class="text-start"><a href="{% url 'sportivity:detail-event' event.id %}">{{event.nama_event}}</a></h6>
							<p style="color: #00BEDA">{{event.host}}</p>
						</div>
						<div class="row post-exerpts">
							<div class="col-6 hiasan">
								{{event.get_jenis_olahraga_display}}
							</div>
							<div class="col-6 hiasan">
								{{event.get_status_display}}
							</div>
							<div class="col-6 hiasan">
								{{event.venue}}
							</div>
						</div>

						<div class="date">
							<h4 class="my-auto">{{event.tanggal}}</span></h4>
						</div>
						<div class="more">
							<a href="{% url 'sportivity:detail-event' event.id %}">Detail</a>
						</div>
					</div>
				</article>
			</div>
			{% endfor %}
		</div>
	</div>
</section>

<div class="block">
	{% for event in list_event %}
	<div class="card mb-3" style="max-width: 18rem;">
		<div class="card-header">{{event.nama_event}}</div>
		<div class="card-body">
			<div class="post-thumb">
				<a href="{% url 'sportivity:detail-event' event.id %}">
					<img src="{% static 'assets-eventre/images/news/post-thumb-one.jpg' %}" alt="post-image"
						class="img-fluid">
				</a>
			</div>
			<h5 class="card-title">{{event.host}}</h5>
		</div>
		<p class="card-text">{{event.get_jenis_olahraga_display}}</p>
		<p class="card-text">{{event.get_status_display}}</p>
		<p class="card-text">{{event.alamat}}</p>
	</div>
	{% endfor %}
</div>
</div>

<!-- JAVASCRIPTS -->
<!-- jQuey -->
<script src="{% static 'assets-eventre/plugins/jquery/jquery.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'assets-eventre/plugins/popper/popper.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'assets-eventre/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Smooth Scroll -->
<script src="{% static 'assets-eventre/plugins/smoothscroll/SmoothScroll.min.js' %}"></script>
<!-- Isotope -->
<script src="{% static 'assets-eventre/plugins/isotope/mixitup.min.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'assets-eventre/plugins/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<!-- Slick Carousel -->
<script src="{% static 'assets-eventre/plugins/slick/slick.min.js' %}"></script>
<!-- SyoTimer -->
<script src="{% static 'assets-eventre/plugins/syotimer/jquery.syotimer.min.js' %}"></script>
<!-- Google Mapl -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>
<script type="text/javascript" src="{% static 'assets-eventre/plugins/google-map/gmap.js' %}"></script>
<!-- Custom Script -->
<script src="{% static 'assets-eventre/js/custom.js' %}"></script>

{% endblock content %}